name: bert_ner
channels:
  - pytorch
  - defaults
  - anaconda
  - nvidia
dependencies:
  - python=3.10
  - cudatoolkit
  - pip
  - pip:
    - torch==2.1.2
    - torchvision
    - datasets==2.14.7
    - cuda-compiler
    - deepspeed
    - huggingface-hub==0.17.3
    - numpy==1.23.0
    - regex==2023.12.25
    - tokenizers==0.14.1
    - tqdm==4.65.0
    - transformers==4.34.0
    - accelerate==0.26.1
    - jsonlines==4.0.0
    - sentencepiece
    - tensorboard
    - tensorboardx
